import stringSimilarity from "string-similarity";
import { cleanName } from "../utils/clean-name.js";

const animeKeywords = [
    "Kengan Ashura",
    "Fruits Basket",
    "Naruto Shippuden",
    "A Couple of Cuckoos",
    "Kaiju No 8",
    "Onmyo Kaiten Re Birth Verse",
    "Os Cavaleiros do Zodíaco: A Saga de Hades",
    "Cancoes da Noite",
    "Gintama",
    "One Piece",
    "Beyblade Burst",
    "Bungo Stray Dogs",
    "100 Namoradas Que Te Amam Muuuuuito",
    "HAIKYU",
    "The Promised Neverland",
    "Ive Been Killing Slimes For 300 Years And Maxed Out My Level",
    "The Rising of the Shield Hero",
    "Chillin in Another World with Level 2 Super Cheat Powers",
    "Os Sete Pecados Capitais Os Quatro Cavaleiros do Apocalipse",
    "Densetsu no Yuusha no Densetsu",
    "Seraph of the End Vampire Reign",
    "Golden Boy",
    "Hamtaro",
    "The Strongest Sage With the Weakest Crest",
    "Go Go Loser Ranger",
    "A Ilha das Sombras",
    "How a Realist Hero Rebuilt the Kingdom",
    "The Ossan Newbie Adventurer Trained to Death by the Most Powerful Party Became Invincible",
    "Diarios de uma Apotecaria",
    "Trigun",
    "Bye Bye Earth",
    "WIND BREAKER",
    "WIND BREAKER",
    "Soul Eater",
    "Zillion",
    "JUNG KOOK I AM STILL THE ORIGINAL",
    "Im a Noble on the Brink of Ruin",
    "A Playthrough of a Certain Dudes VRMMO Life",
    "Super Cubo",
    "Wistoria Wand and Sword",
    "Spy x Family",
    "Solo Leveling",
    "Meu Casamento Feliz",
    "Jujutsu Kaisen",
    "Re ZERO Starting Life in Another World",
    "Dr Stone",
    "Boku no Hero Academia",
    "Initial D",
    "BOCCHI THE ROCK",
    "Dragon Ball Z Kai",
    "Plunderer",
    "My Hero Academia",
    "One Piece",
    "Wakfu",
    "Cyberpunk Mercenarios",
    "I Left my A Rank Party to Help My Former Students Reach the Dungeon Depths",
    "Boruto Naruto Next Generations",
    "A Sign of Affection",
    "Shangri La Frontier",
    "Im Getting Married to a Girl I Hate in My Class",
    "Ameku M D Doctor Detective",
    "OKITSURA",
    "Grisaia Phantom Trigger",
    "Medalist",
    "Bakugan Guerreiros da Batalha",
    "Seirei Gensouki Spirit Chronicles",
    "Yu-Gi-Oh! Sevens",
    "Yu-Gi-Oh! Go Rush!!",
    "Yu-Gi-Oh! GX",
    "Attack on Titan",
    "Zatch Bell",
    "DEMON LORD 2099",
    "Blue Lock",
    "Captain Tsubasa",
    "Hunter x Hunter",
    "Sword Art Online",
    "Castlevania Noturno",
    "By the Grace of the Gods",
    "Noblesse",
    "Beast Tamer",
    "Ai Tenchi Muyo",
    "REBORN",
    "Rougo ni Sonaete Isekai de 8-manmai no Kinka wo Tamemasu",
    "Rent a Girlfriend",
    "Reencarnado numa Maquina de Vendas Agora Exploro a Masmorra",
    "Monster",
    "Masamune kun s Revenge",
    "Tokyo Revengers",
    "Demon Slayer Kimetsu no Yaiba",
    "Paradox Live THE ANIMATION",
    "My New Boss is Goofy",
    "Fire Force",
    "100 man no Inochi no Ue ni Ore wa Tatte Iru",
    "Bleach Thousand Year Blood War",
    "The Hidden Dungeon Only I Can Enter",
    "VTuber Legend How I Went Viral after Forgetting to Turn Off My Stream",
    "11eyes",
    "FLCL",
    "The Eminence in Shadow",
    "Smile Precure",
    "Hungry Heart",
    "Keep Your Hands Off Eizouken",
    "Os Cavaleiros do Zodiaco A Saga De Asgard",
    "That Time I Got Reincarnated as a Slime",
    "Food Wars Shokugeki no Soma",
    "A Serie Pokemon Horizontes",
    "Brave Bang Bravern",
    "Boku no Kokoro no Yabai Yatsu",
    "Wise Mans Grandchild",
    "Super Campeoes Rumo ao Sonho",
    "D Gray Man",
    "Migi e Dali",
    "Farmacia Mundo Paralelo",
    "4 Cut Hero",
    "Tengoku Daimakyo Ilusao Celestial",
    "A Journey Through Another World Raising Kids While Adventuring",
    "Blue Dragon",
    "I Was Reincarnated as the 7th Prince so I Can Take My Time Perfecting My Magical Ability",
    "7th Time Loop The Villainess Enjoys a Carefree Life Married to Her Worst Enemyv",
    "Naruto",
    "Dragon Ball",
    "The Rising of the Shield Hero",
    "Onimusha",
    "PLUTO",
    "Violet Evergarden",
    "Street Fighter II Victory",
    "Dragon Ball GT",
    "Megalo Box",
    "Juushinki Pandora",
    "Revisions",
    "Os Kabanes da Estacao de Ferro",
    "GOBLIN SLAYER",
    "MASHLE MAGIA E MUSCULOS",
    "A Concierge Pokemon",
    "Campfire Cooking in Another World with My Absurd Skill",
    "Kannagi",
    "Yu-Gi-Oh! Arc-V",
    "Yu☆Gi☆Oh! VRAINS",
    "Ishura",
    "The Unwanted Undead Adventurer",
    "Villainess Level 99 I May Be the Hidden Boss But Im Not the Demon Lord",
    "Hells Paradise",
    "Dungeon Meshi",
    "Yu-Gi-Oh!",
    "Monster Rancher",
    "The Weakest Tamer Began a Journey to Pick Up Trash",
    "Cronicas de um Aristocrata em Outro Mundo",
    "BUCCHIGIRI?!",
    "Shaman King Flowers",
    "Tales of Wedding Rings",
    "The Fire Hunter",
    "Ragna Crimson",
    "Frieren e a Jornada para o Alem",
    "Delusional Monthly Magazine",
    "Hokkaido Gals Are Super Adorable",
    "Metallic Rouge",
    "Hotel Hazbin",
    "The Demon Prince of Momochi House",
    "ARK The Animated Series",
    "Re Monster",
    "Como Raeliana Foi Parar na Mansão do Duque",
    "Super Onze",
    "Fairy Tail",
    "National Kid",
    "Dark Gathering",
    "Rikei ga Koi ni Ochita no de Shoumei shitemita",
    "A Salad Bowl of Eccentrics",
    "Aishiteruze Baby",
    "An Archdemon s Dilemma How to Love Your Elf Bride",
    "As a Reincarnated Aristocrat I ll Use My Appraisal Skill to Rise in the World",
    "Astro Note",
    "Blue Archive The Animation",
    "Blue Archive The Animation",
    "Date A Live",
    "GIRLS BAND CRY",
    "HIGHSPEED Etoile",
    "Our Dating Story The Experienced You and The Inexperienced Me",
    "The Banished Former Hero Lives as He Pleases LEG",
    "22 7  nanabun no nijyuuni",
    "BOFURI I Don t Want to Get Hurt  so I ll Max Out My Defense",
    "Ranking of Kings",
    "Seiken Gakuin no Makentsukai",
    "Tari Tari",
    "Yuusha ni Narenakatta Ore wa Shibushibu Shuushoku wo Ketsui Shimashita",
    "Dragon Raja The Blazing Dawn",
    "Fullmetal Alchemist: Brotherhood",
    "Muv Luv Alternative  Total Eclipse",
    "Gekidol",
    "Gundam Build Fighters",
    "Kirakira Precure A La Mode",
    "Cardfigh Vanguard overDress",
    "Super Campeões: Rumo ao Sonho",
    "Alya Sometimes Hides Her Feelings in Russian",
    "Fontes Termais de Outro Mundo",
    "Lv2 kara Cheat datta Motoyuusha Kouho no Mattari Isekai Life",
    "CODE GEASS Roze da Reconquista",
    "The Misfit of Demon King Academy",
    "The Vexations of a Shut In Vampire Princess",
    "E Serio Que Eu Sou o Mais Forte",
    "Cardcaptor Sakura",
    "TSUKIMICHI Moonlit Fantasy",
    "Os Cavaleiros do Zodíaco",
    "The Gene of AI",
    "Saiki Kusuo no Psi nan Reativado",
    "Bucky",
    "Shadows House",
    "Mahoutsukai Reimeiki",
    "Meu Trabalho no Cafe Yuri",
    "Sword of the Demon Hunter Kijin Gentosho",
    "Levius",
    "Mushikago no Cagaster",
    "7SEEDS",
    "Bleach",
    "Cannon Busters",
    "Dragon Ball Z",
    "Dorohedoro",
    "Digimon Adventure",
    "Dragon's Dogma",
    "Great Pretender",
    "Yasuke",
    "Edens Zero",
    "HIGH SCORE",
    "Aoashi",
    "Dragon Quest: Dai no Daibouken",
    "Vampiro no Jardim",
    "Dota Dragons Blood",
    "Kakegurui Twin",
    "Chainsaw Man",
    "Baki",
    "Revenger",
    "Make My Day",
    "Tokyo Ghoul",
    "BASTARD!!",
    "Record of Ragnarok",
    "Samurai Warriors",
    "Black Clover",
    "One Punch Man",
    "Shuumatsu no Harem",
    "Ganhei um Poder Apelao em Outro Mundo e Agora Sou Imbativel no Mundo Real",
    "Kono Subarashii Sekai ni Bakuen Wo",
    "Death Note",
    "Yu Yu Hakusho",
    "Baki O Campeao",
    "Baki Hanma",
    "86 Eighty Six",
    "Os Cavaleiros do ZodIaco Omega",
    "Overlord",
    "Hellsing",
    "2020 Japao Submerso",
    "Joker Game",
    "Assassination Classroom",
    "VINLAND SAGA",
    "Mushoku Tensei Jobless Reincarnation",
    "Dragon Ball Super",
    "Akuma kun",
    "Akame ga Kill",
    "Tensura Nikki Tensei shitara Slime Datta Ken"
];

export function isAnime(stream) {
  let score = 0;

  // Gênero Animation tem mais peso
  if (stream?.tmdb?.genre_ids?.includes(16)) score += 3;

  // País Japão
  if (stream?.tmdb?.origin_country?.includes("JP")) score += 2;

  // Idioma original japonês
  if (stream?.tmdb?.original_language === "ja") score += 1;

  if (stream?.category_names?.toLowerCase()?.includes('anime')) {
    return true;
  }
  // Nome/keywords
  const title = cleanName(stream?.title?.toLowerCase()) ?? cleanName(stream?.stream_display_name?.toLowerCase());
  const match = stringSimilarity.findBestMatch(title, animeKeywords.map(n => n.toLowerCase()));
  if (match.bestMatch.rating > 0.6) score += 1;

  return score >= 3; // threshold para considerar anime
}