import stringSimilarity from "string-similarity";
import { cleanName } from "../utils/clean-name.js";

// Lista de doramas famosos no Brasil
const doramaKeywords = [
    "Amor Alem do Tempo",
    "Linha S",
    "Loucos Um Pelo Outro",
    "Questao de Tempo",
    "Nosso Eterno Verao",
    "Doce Engano",
    "Amor Casamento e Divorcio",
    "Amanha",
    "Amor e Outros Dramas",
    "Come Back Mister",
    "Wild Romance",
    "Uma Dose Diaria de Sol",
    "Behind Your Touch",
    "Amor e Batatas",
    "Se a Vida Te Der Tangerinas...",
    "O Conto de Nove Caudas",
    "Ela Era Bonita",
    "Diva a Deriva",
    "Do Dia Para a Noite",
    "Fadas da Limpeza",
    "O Amor Volta para Casa",
    "Com Carinho Kitty",
    "The 8 Show",
    "LoveSick",
    "18 Outra Vez",
    "Minha Venus",
    "Love is a Poison",
    "Doctor Detective",
    "Less Than Evil",
    "Beach Boys",
    "Dragoes de Wonderhatch",
    "Flores no Deserto",
    "The King Eternal Monarch",
    "Mystic Pop up Bar",
    "Memorias de Alhambra",
    "Chocolate",
    "Branding in Seongsu",
    "Café Minamdang",
    "Bake Me Please",
    "A Lua Abraca o Sol",
    "A Cadela Sabichona",
    "A Ilha",
    "My Runway",
    "My Lovely Liar",
    "My Lovely Boxer",
    "Fogos de Artificio do Meu Coraçao",
    "Goblin",
    "Bulgasal Almas Imortais",
    "Iris",
    "O Dia do Sequestro",
    "Beleza Verdadeira",
    "Amor de Intermediario",
    "A Vinganca do Casamento Perfeito",
    "De Volta as Raizes",
    "Em Movimento",
    "Pousando no Amor",
    "Misty",
    "Cherry Magic",
    "Last Twilight",
    "Big Mouth De Vigarista a Vingador",
    "Rainha das Lagrimas",
    "Dr Romantico",
    "Amor Oculto",
    "Uma Familia Inusitada",
    "Conexao Comer Amar e Matar",
    "The K2",
    "Primeira Vez Amor",
    "Um Bom Dia para Ser um Cachorro",
    "Florescendo",
    "Tio Samsik",
    "Noble My Love",
    "Signal",
    "Sonata de Inverno",
    "Beleza Interior",
    "Agora Terminamos",
    "Doctor Prisoner",
    "Namoro na Cozinha",
    "O Sacerdote Impetuoso",
    "O Voto de Morte",
    "Pinoquio",
    "Rattan",
    "Eu Ouco a Sua Voz",
    "Adoravel Corredora",
    "Meu doce mafioso",
    "Strong Girl Nam soon",
    "A Princesa Real",
    "Anjos caem as vezes",
    "Guerra Korea Khitan War",
    "Juvenile Justice",
    "A Cobertura",
    "Peoes do Amor",
    "Nosso Destino",
    "O Rei de Porcelana",
    "Holo Meu Amor",
    "Stay With Me",
    "Queridos Amigos",
    "Um Homem Sem Filtros",
    "Kanojo Okarishimasu",
    "The K2",
    "O Pior do Mal",
    "Salve Me",
    "A Caminho do Ceu",
    "Love Alarm",
    "Retaliação",
    "Vincenzo",
    "Dr Brain",
    "Hospital Playlist",
    "Alice in Borderland",
    "Enfermeira Exorcista",
    "Passarela de Sonhos",
    "Apaixonados na Cidade",
    "Apostando Alto",
    "Law School",
    "Na Direcao do Amor",
    "Uma Noite de Primavera",
    "Romance is a Bonus Book",
    "O Rei Eterno",
    "Quando Meu Amor Floresce",
    "O Mar da Tranquilidade",
    "All of Us Are Dead",
    "Alquimia das Almas",
    "Amanha",
    "Apesar de Tudo, Amor",
    "Backstreet Rookie",
    "Clube das Mães",
    "Rookie Historian Goo Hae-Ryung",
    "Hometown Cha Cha Cha",
    "Match VIP",
    "O Que Houve com a Secretária Kim?",
    "Oh My Baby",
    "O Som da Magia",
    "Um Pesadelo de Casamento",
    "Clima do Amor",
    "Hi Bye Mama",
    "Vinte e Cinco Vinte e Um",
    "Stranger",
    "Intensivao de Amor",
    "Love to Hate You",
    "Interligados",
    "Doutor Advogado",
    "First Love",
    "Cacadores de Demonios",
    "Em Busca de Vinganca",
    "A Jornalista",
    "Amor Rural",
    "Argon",
    "E Tudo Meu",
    "Somebody",
    "Goedam",
    "The Guest",
    "The Fabulous",
    "A Licao",
    "Flower of Evil",
    "Good Morning Call",
    "O Vento Sopra",
    "Os Casamenteiros de Joseon",
    "Grande Amor",
    "Meu Querido Guerreiro",
    "Esposa em Tempo Integral",
    "Isso Se Chama Amor",
    "Nao Quero Fazer Nada",
    "O Bonde",
    "Ariyoshi ao Resgate",
    "Um Advogado por um Dolar",
    "Tigre e Dragao",
    "The Good Bad Mother",
    "Desgraca ao seu Dispor",
    "Vejo Voce na Proxima Vida",
    "O Advogado de Divorcio",
    "Pretendente Surpresa",
    "Uma Advogada Extraordinaria",
    "Divorciados",
    "Descendentes do Sol",
    "Sorriso Real",
    "Mask Girl",
    "O Tempo Traz Voce pra Mim",
    "Em Movimento",
    "Caes de Caca",
    "A Lenda Um Luxo de Sonhar",
    "Dra Cha",
    "Yonder",
    "Duzentos Anos de Amor",
    "Meu Amor das Estrelas"
];

export function isDorama(stream) {
  let score = 0;

  // 🎭 Categoria soap
  if (stream?.tmdb?.genre_ids?.includes(10766)) {
    score += 3;
  }

  // 🌏 País (KR, JP, CN, TW)
  if (stream?.tmdb?.origin_country?.some(c => ["KR", "JP", "CN", "TW"].includes(c))) {
    score += 2;
  }

  // 🔎 Nome
  const title = cleanName(stream?.title?.toLowerCase()) ?? cleanName(stream?.stream_display_name?.toLowerCase());
  const match = stringSimilarity.findBestMatch(title, doramaKeywords.map(n => n.toLowerCase()));
  if (match.bestMatch.rating > 0.6) {
    score += 1;
  }

  if (stream?.category_names?.toLowerCase()?.includes('dorama')) {
    return true;
  }

  // ✅ Retorna true só se realmente tiver relevância
  return score >= 3;
}