name: release

on:
  workflow_dispatch:
    inputs:
      increment:
        type: choice
        description: 'Tipo de incremento: patch, minor, major ou pre*'
        required: true
        default: 'patch'
        options:
          - patch
          - minor
          - major
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.3

      - name: Install Dependencies
        run: npm ci || npm install

      - name: Release Version
        run: npx release-it --increment ${{ github.event.inputs.increment }}